version: "3.8"

services:
    nginx-godhand:
        image: nginx:1.23
        restart: always
        tty: true
        ports:
            - "${DC_SUBNET}:80:80"
        volumes:
            - ./nginx/templates:/etc/nginx/templates
            - ../:/var/www
        environment:
            APP_DIR: /var/www
        links:
            - php-godhand
        networks:
            godhand-network:
                aliases:
                    - ${DC_APP_DOMAIN}

    db-godhand:
        image: mysql:8.0
        restart: always
        tty: true
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake
            - --default_authentication_plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        ports:
            - "${DC_SUBNET}:3306:3306"
            - "${DC_SUBNET}:33060:33060"
        volumes:
            - "${MYSQL_STORAGE_DIR}:/var/lib/mysql"
        networks:
            - godhand-network

    redis-godhand:
        image: redis:latest
        restart: always
        tty: true
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "${DC_SUBNET}:6379:6379"
        networks:
            - godhand-network

    php-godhand:
        restart: always
        tty: true
        build:
            context: ./php
        environment:
            XDEBUG_CONFIG: client_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=${DC_PROJECT_NAME}"
            APP_DOMAIN: "${DC_APP_DOMAIN}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_PORT: "3306"
        ports:
            - "${DC_SUBNET}:9000:9000"
        volumes:
            - ../:/var/www
        depends_on:
            - db-godhand
        links:
            - db-godhand
            - redis-godhand
        networks:
            - godhand-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        dns:
            - 8.8.8.8


networks:
    godhand-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "${DC_SUBNET}/24"



